#!/bin/bash

title=$1
titleSlug=$(echo "${title}" | sed 's/ /-/g')

header=$(cat <<- EOF 
---
title: $title
date: $(date -u -Iseconds)
description: $title
---
EOF
)

mkdir "content/blog/${titleSlug}"
echo "$header" > "content/blog/${titleSlug}/${titleSlug}.md"