#!/bin/bash

title=$1
titleSlug=$(echo "${title}" | sed 's/ /-/g')
dt=$(date -u -I)

header=$(cat <<- EOF 
---
title: $title
date: $dt
description: $title
---
EOF
)

echo "$header" > "posts/${dt}-${titleSlug}.md"
git add "posts/${dt}-${titleSlug}.md"
